Update requirements.txt
This dependency also needs to be installed in order to avoid this error - 
Traceback (most recent call last):
  File "/app/./run.py", line 4, in <module>
    from server.website import Website
  File "/app/server/website.py", line 2, in <module>
    from flask_babel import refresh
ModuleNotFoundError: No module named 'flask_babel'